Remove cassandra-all
ing-bank/cassandra-jdbc-wrapper pull request #6
Opened 2022-03-04 10:01 UTC by mjok

this prone to collect vulnerable libs and sparsely used.
I think code copy would benefit more.

2022-03-05 10:29 UTC, maximevw commented
Hello @mjok,
Thanks a lot for your pull request. I will review it as soon as possible.
Could you please modify it to merge into `release/next` branch as requested in our contributing policy? We´ll take advantage of your changes to build and release a new minor version (4.6.0) including other changes already included into this branch.

2022-03-10 05:53 UTC, maximevw commented
Hello @mjok
Did you see the other comments on the pull request or didn't have you just the time to review them?

2022-03-10 08:19 UTC, mjok commented
Didn't saw any comment other than branch to merge. Can't see any them either now

2022-03-10 08:37 UTC, maximevw requested changes

2022-03-10 08:38 UTC, maximevw commented
> Didn't saw any comment other than branch to merge. Can't see any of them now. I did change the branch.

Sorry @mjok, my bad... I forgot to submit my review 😄

2022-03-10 08:55 UTC, mjok commented on pom.xml
> +            <groupId>com.google.guava</groupId>
com/ing/data/cassandra/jdbc/CassandraConnection.java:22
uses com.google.common.collect.Maps;

2022-03-10 09:41 UTC, maximevw commented on pom.xml
> +            <groupId>com.google.guava</groupId>
Right. I missed it. 
Could you please manage the Guava version in the section `<properties>` of the POM file as for the other dependencies?
I note to patch this as soon as possible :)

2022-03-14 12:27 UTC, maximevw approved these changes
I'll prepare the release 4.6.0 very soon including these changes.
Thank you @mjok for your contribution.

2022-03-14 12:27 UTC, merged